# Generated by Django 5.1.2 on 2024-11-05 14:54

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to=polls.models.user_directory_path, validators=[polls.models.validate_file_size]),
        ),
    ]
