# Generated by Django 5.1.2 on 2024-11-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='create_date',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='owner',
            new_name='user',
        ),
    ]
